datasources:
  default:
    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1
    username: sa
    password: ""
    driverClassName: org.h2.Driver

jpa:
  default:
    packages-to-scan:
      - 'com.github.larsq.spektx.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true